### ISSUE TITLE
make "training.arc42.org" a site that's useful on its own...

### ISSUE THREAD

**Issue by gernotstarke** [arc42/trainings.arc42.org-site#1]
Important: This site MUST BE USABLE without JavaScript (people having JS enabled or are allowed to use it will get this info on the other arc42 sites)

The css here shall be different from the styling used on the other sites

**Comment by gernotstarke** [comment]
maybe that requires to merge frontend and backend into a single (this) repository. Not urgent - maybe we discuss it when we talk about the Vercel-account issue...

**Comment by Per-Starke** [comment]
done, backend and frontend merged in this repo, vercel linked to the /api directory here, and subtle-ads html included in this repo via jekyll includes instead of js
