### ISSUE TITLE
from dates.arc42.org, add a redirect to trainings.arc42.org

### ISSUE THREAD

**Issue by gernotstarke** [arc42/trainings.arc42.org-site#3]
maybe we do this for the following subdomains too:

[x] training.arc42.org
[x] dates.arc42.org
[ ] training.arc42.de
[ ] trainings.arc42.de

We need @Hruschka to create the arc42.de subdomains, though.

See also [this chatGPT prompt](https://chat.openai.com/c/5bddad72-b4ed-46e2-98db-f2532f20db09)

**Comment by gernotstarke** [comment]
scheint zu klappen, bei HostEurope den CNAME für die dates & training auf "trainings.arc42.org" gesetzt...

**Comment by gernotstarke** [comment]
bei dates.arc42.org ebenso gemacht

**Comment by Per-Starke** [comment]
@gernotstarke Also ich hab die Site jetzt unter [trainings.arc42.org](https://trainings.arc42.org) veröffentlicht, das geht schonmal :)

Die redirects von training und date funktionieren bei mir aber gerade nicht.. Geht das bei dir?

**Comment by Per-Starke** [comment]
@gernotstarke Are we still doing anything on this one?

**Comment by gernotstarke** [comment]
wontfix.
