### ISSUE TITLE
I need to connect vercel with this repo

### ISSUE THREAD

**Issue by Per-Starke** [arc42/trainings.arc42.org-site#4]
But I can't, as I'm not the organization owner... Did you get an email @gernotstarke? If yes, please accept that, if not, we need to check..

**Comment by gernotstarke** [comment]
I just approved the connection request.
Had to approve it for ALL repositories, as I could not select only the training-repo... (#wtf)

**Comment by Per-Starke** [comment]
Yep, #wtf, but awesome, then I can continue!
